name: release

on: dispatch

jobs:
  linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - run: flutter build linux
      - name: Zips the build
        uses: papeloto/action-zip@v1
        with:
          files: build/linux/x64/release/bundle/
          dest: centipede.zip
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: centipede
          path: centipede.zip
